# Generated by Django 4.2.7 on 2024-01-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
    ]
