# Generated by Django 4.2.7 on 2024-01-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_portfolio_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
    ]
